services:
  postgres:
    image: postgres:15.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
  pgAdmin:
    image: dpage/pgadmin4:8.0
    ports:
      - "2000:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0
      - PGADMIN_DEFAULT_PASSWORD=admin
  yarn-container:
    image: node:22.5
    volumes:
      - ./:/home/tiles-tbd:rw
    working_dir: /home/tiles-tbd
    tty: true
    stop_grace_period: 1s
    command: tail -f /dev/null
  api:
    image: node:22.5
    volumes:
      - ./:/home/tiles-tbd:rw
    working_dir: /home/tiles-tbd/packages/api
    command: bash -c "corepack enable && yarn && cd ../../ && yarn dev api"
  backend:
    image: node:22.5
    ports:
      - '8080:8080'
    volumes:
      - ./:/home/tiles-tbd:rw
    working_dir: /home/tiles-tbd/packages/backend
    environment:
      - PORT=8080
      - DATABASE=postgresql://postgres@host.docker.internal:5432/tiles-tbd?schema=public
    command: bash -c "corepack enable && yarn && cd ../../ && yarn dev backend"
  frontend:
    image: node:22.5-slim
    ports:
      - '3000:3000'
    volumes:
      - ./:/home/tiles-tbd:rw
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    working_dir: /home/tiles-tbd/packages/frontend
    command: bash -c "corepack enable && yarn && cd ../../ && yarn dev frontend"