services:
  postgres:
    container_name: postgres
    image: postgres:15.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=trust
  pgAdmin:
    container_name: pg_admin
    image: dpage/pgadmin4:8.11
    ports:
      - "2000:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
  yarn-container:
    container_name: yarn
    image: node:23.11.0
    volumes:
      - ./:/home/resync-games:rw
    working_dir: /home/resync-games
    tty: true
    stop_grace_period: 1s
    environment:
      - GAME_STATE_DATABASE_HOST_URL=${GAME_STATE_DATABASE_HOST_URL}
      - GAME_STATE_DIRECT_URL=${GAME_STATE_DIRECT_URL}
    command: tail -f /dev/null
  backend:
    container_name: backend
    image: node:23.11.0
    ports:
      - '8080:8080'
    volumes:
      - ./:/home/resync-games:rw
    working_dir: /home/resync-games/packages/backend
    environment:
      - GAME_ORCHESTRATOR=true
      - GAME_STATE_DATABASE_HOST_URL=${GAME_STATE_DATABASE_HOST_URL}
      - GAME_STATE_DIRECT_URL=${GAME_STATE_DIRECT_URL}
      - PUBLIC_URL=${PUBLIC_URL}
    command: bash -c "corepack enable && yarn && cd ../../ && yarn db:migrate && yarn dev backend"
  frontend:
    container_name: frontend
    image: node:23.11.0-slim
    ports:
      - '3000:3000'
    volumes:
      - ./:/home/resync-games:rw
    environment:
      - NEXT_PUBLIC_API_URL=http://${LOCAL_HOST}:8080
      - NEXT_PUBLIC_API_CLIENT_URL=http://${PUBLIC_URL}:8080
    working_dir: /home/resync-games/packages/frontend
    command: bash -c "corepack enable && yarn && cd ../../ && yarn dev frontend"