services:
  postgres:
    image: postgres:15.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=trust
  pgAdmin:
    image: dpage/pgadmin4:8.11
    ports:
      - "2000:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
  yarn-container:
    image: node:22.5
    volumes:
      - ./:/home/resync-games:rw
    working_dir: /home/resync-games
    tty: true
    stop_grace_period: 1s
    environment:
      - DATABASE_HOST_URL=postgresql://postgres:${POSTGRES_PASSWORD}@${LOCAL_HOST}:5432/resync-games?schema=public
    command: tail -f /dev/null
  api:
    image: node:22.5
    volumes:
      - ./:/home/resync-games:rw
    working_dir: /home/resync-games/packages/api
    command: bash -c "corepack enable && yarn && cd ../../ && yarn dev api"
  games:
    image: node:22.5
    volumes:
      - ./:/home/tiles-tbd:rw
    working_dir: /home/tiles-tbd/packages/games
    command: bash -c "corepack enable && yarn && cd ../../ && yarn dev games"
  backend:
    image: node:22.5
    ports:
      - '8080:8080'
    volumes:
      - ./:/home/resync-games:rw
    working_dir: /home/resync-games/packages/backend
    environment:
      - PORT=8080
      - DATABASE_HOST_URL=postgresql://postgres:${POSTGRES_PASSWORD}@${LOCAL_HOST}:5432/resync-games?schema=public
    command: bash -c "corepack enable && yarn && cd ../../ && yarn migrate && yarn dev backend"
  frontend:
    image: node:22.5-slim
    ports:
      - '3000:3000'
    volumes:
      - ./:/home/resync-games:rw
    environment:
      - NEXT_PUBLIC_API_URL=http://${LOCAL_HOST}:8080
      - NEXT_PUBLIC_API_CLIENT_URL=http://${PUBLIC_URL}:8080
    working_dir: /home/resync-games/packages/frontend
    command: bash -c "corepack enable && yarn && cd ../../ && yarn dev frontend"