export const WORD_IDEAS = [
  "Your favorite childhood TV character",
  "Your least favorite adjective",
  "A less popular color",
  "A popular song right now",
  "Your most recent trip's destination",
  "A random city in your state",
  "An article of clothing someone in the group is wearing",
  "Your favorite snack as a kid",
  "A job you'd never want",
  "A word you can't spell on the first try",
  "A famous person with the same first name as you",
  "Something you'd find in your fridge right now",
  "A fictional place you wish you could visit",
  "A sport you don't understand",
  "A food you hate but others love",
  "Something you're allergic to (or would be scared to be allergic to)",
  "A random sound you like",
  "The last thing you bought",
  "A hobby you tried and quit",
  "A plant you know the name of",
  "A celebrity you'd be awkward around",
  "Something you always forget to pack",
  "A bad haircut style",
  "A holiday tradition from your family",
  "A word that always makes you laugh",
  "A childhood fear",
  "A brand you're irrationally loyal to",
  "A kitchen tool you never use",
  "A useless talent you have",
  "A song lyric that always gets stuck in your head",
  "A smell that reminds you of home",
  "A dance move you know",
  "Something you've accidentally broken",
  "A made-up word you use",
  "A candy you'd trade away",
  "A store you never go into",
  "A famous duo (real or fictional)",
  "A creature that freaks you out",
  "A game you always lose",
  "A hairstyle you once had",
  "An animal you wish could talk",
  "Something you pretend to like",
  "A piece of slang from your teen years",
  "Something you whisper",
  "A teacher you remember (just the name)",
  "Something you've Googled recently",
  "A type of weather you secretly love",
  "The name of a stuffed animal you had",
  "A type of soup that someone in the group loves",
  "Something people collect",
  "A shape that people don't like",
  "Something that squeaks",
  "An outdated technology",
  "A way to get famous",
  "A phrase your family says",
  "A sound effect you can make",
  "A thing people clap for",
  "Something you'd never eat on a first date",
  "A noise your pet makes",
  "A trend you don't understand",
  "A strange item in your junk drawer",
  "Your go-to karaoke song",
  "A word that rhymes with 'orange' (or almost does)",
  "Your dream job as a 5-year-old",
  "Something you do when no one's watching",
  "A brand name you mispronounced as a kid",
  "A book you never finished",
  "A chore you avoid",
  "Something you'd shout if you were on a roller coaster",
  "A thing you're always losing",
  "A smell you can't stand",
  "A phrase that sounds weird if you say it 10 times",
  "Something you only do on vacation",
  "An item you've owned forever",
  "The worst flavor of ice cream",
  "Something you use every day but don't know how it works",
  "The name of a childhood imaginary friend",
  "A way to embarrass yourself instantly",
  "Something you'd find under a couch",
  "An object you'd bring to a desert island",
  "A guilty pleasure TV show",
  "A character from a nursery rhyme",
  "An emoji you use too much",
  "Something that makes a crunch sound",
  "An item you always forget at the grocery store",
  "A dessert your grandma made",
  "A bad smell you secretly like",
  "A pet name someone has called you",
  "Something you can't do without looking",
  "A conspiracy theory",
  "Something you whisper in a library",
  "A dance move from the '90s",
  "A job robots shouldn't do",
  "A toy from your childhood",
  "A word that sounds fancy",
  "A famous person with a strange voice",
  "A word that sounds fake but is real",
  "A bad gift you've received",
  "A party theme gone wrong",
  "A celebrity you'd switch lives with for a day",
  "A sound from nature",
  "A game you always cheat at",
  "A flavor that should never be gum",
  "Something you yell at your TV",
  "An animal with a funny walk",
  "A lie you believed as a kid",
  "Something you'd say to get out of a speeding ticket",
  "A way to ruin a surprise party",
  "Something that could be haunted",
  "A face you make when you're confused",
  "A name you'd give a goldfish",
  "A random object in your car",
  "A catchphrase from a cartoon",
  "An annoying commercial jingle",
  "A word that sounds cooler in another language",
  "A type of hat",
  "A smell from a carnival",
  "A sound babies make",
  "A way to annoy your sibling",
  "A school lunch item you dreaded",
  "A phrase you'd never want on a T-shirt",
  "A word you just like the sound of",
  "A classic board game",
  "An awkward text message",
  "Something you've tripped over",
  "A color name that sounds made-up",
  "A made-up superhero power",
  "A weird law from somewhere",
  "A phrase you'd never hear in a horror movie",
  "A weird award to win",
  "A name for a pet rock",
  "A food that's better cold",
  "Something you'd find in a time capsule",
  "An activity you can't do in space",
  "A word you misheard in a song",
  "Something you'd yell in frustration",
  "An expression your grandparents use",
  "A brand that sounds like a person's name",
  "A weird reason to miss work",
  "Something you wouldn't want in your shoe",
  "A thing that goes bump in the night",
  "A bedtime ritual",
  "A famous movie quote",
  "A nickname you hated",
  "Something only a toddler would say",
  "A superstition you've heard of",
  "A weird food combo someone swears by",
  "A slang word that should stay in the past",
  "Something you wouldn't want to see in your mirror",
  "A funny way to greet someone",
  "An invention you think is pointless",
  "Something that only happens in cartoons",
  "The name of a soap opera",
  "A made-up holiday",
  "Something you'd bring to a costume party",
  "An animal you'd ride into battle",
  "A job you'd be terrible at",
  "Something people hoard",
  "A sound you make when you're scared",
  "A word that makes you cringe",
  "A weird nickname for your phone",
  "Something that wiggles",
  "A sentence you'd never say in public",
  "Your favorite breakfast food",
  "A movie you've seen more than five times",
  "A toy you loved as a kid",
  "Something you'd bring to a picnic",
  "A sound you can imitate",
  "A holiday you wish happened more than once a year",
  "Something you might find at the beach",
  "A superhero catchphrase",
  "A silly dance move",
  "A character from a fairy tale",
  "A fruit that's fun to eat",
  "An animal that waddles",
  "A word that sounds funny",
  "Something you'd bring on a camping trip",
  "A place you'd love to visit",
  "A sport you'd like to try",
  "Your favorite kind of weather",
  "A cartoon character's voice you can do",
  "A food that's messy to eat",
  "A famous landmark",
  "A sound you hear at night",
  "Something you do before bed",
  "A song that makes you want to dance",
  "An instrument you'd like to play",
  "Something you always lose",
  "A silly nickname",
  "A hobby you enjoy",
  "A snack you'd take to the movies",
  "A thing that goes up and down",
  "Your favorite holiday tradition",
  "Something you can build with blocks",
  "A dessert with sprinkles",
  "A job that sounds fun",
  "A funny animal name",
  "A type of cereal",
  "Something you do when you're bored",
  "A word that rhymes with 'cake'",
  "A silly face you make",
  "Something you find in a tree",
  "A game you like to play",
  "A color that sounds like a fruit",
  "A toy that makes noise",
  "Something that spins",
  "An animal that lives in the water",
  "Something you blow air into",
  "A breakfast item you can eat with your hands",
  "A sound you make when you're surprised",
  "A thing with wheels",
  "A word that starts with Z",
  "A type of bug",
  "Something cold and delicious",
  "A place you go to relax",
  "Something you shout when you win",
  "Something people do on their birthday",
  "A silly animal noise",
  "A treat you can roast over a fire",
  "A food you eat with a spoon",
  "Something that bounces",
  "A type of hat",
  "Something you wear on your feet",
  "An animal you've seen at a zoo",
  "A fun thing to do in the snow",
  "A famous mouse",
  "A word with double letters",
  "Something that smells good",
  "A thing you build with your hands",
  "A shape with more than 4 sides",
  "A type of sandwich",
  "Something that floats",
  "A thing that comes in a box",
  "Something you use when it's raining",
  "A word that makes you smile",
  "A mode of transportation",
  "Something you'd see at a carnival",
  "An animal with stripes",
  "Something soft and squishy",
  "A funny word to say three times fast",
  "Something you see in the sky",
  "A type of pasta",
  "Something you wear when it's cold",
  "A kind of pet someone might have",
  "A silly thing someone might do in a mirror",
  "Something you do when you're happy",
  "A food you have to peel",
  "Something that grows in a garden",
  "A holiday decoration",
  "Something you hear at a birthday party",
  "A tool you use in the kitchen",
  "A sound that makes you giggle",
  "Something that pops",
  "A name you'd give a robot",
  "A famous book or story character",
  "Something you see on a farm",
  "A place you can get lost in (in a fun way)",
  "A topping you put on ice cream",
  "A thing that moves fast",
  "Something you'd pack for a road trip",
  "A word that kids often mispronounce",
  "Something you'd find in outer space",
  "A phrase you might hear in a cartoon",
  "A fun thing to do in the summer",
  "Something you'd build out of snow",
  "A noise an animal makes",
  "A flavor of ice cream",
  "Something that glows in the dark",
  "A type of flower",
  "Something sticky",
  "A silly thing to wear on your head",
  "A way to say hello",
  "Something that makes you laugh",
  "A bug with wings",
  "A way to get around without a car",
  "Something colorful",
  "A funny shape",
  "A magical creature",
  "A kind of tree",
  "Something you do when you're excited",
  "Something you'd find in a backpack",
  "A flavor you love",
  "A toy that rolls",
  "A vegetable you like",
  "A word that sounds like its meaning",
  "Something fluffy",
  "A thing you can jump on",
  "A famous animal character",
  "A sound effect from a movie",
  "A type of cheese",
  "Something you'd wear to a costume party",
  "Something you'd build out of LEGOs",
  "A word that rhymes with 'ball'",
  "A sport you play with a ball",
  "A musical instrument you blow into",
  "Something you open with a key",
  "A type of fruit you can slice",
  "A silly rule for a game",
  "Something that lives in a shell",
  "A chore you don't mind doing",
  "A cozy place to read a book",
  "A favorite thing to do on a rainy day",
  "Something shiny",
  "A snack you can't stop eating",
  "A place where animals live",
  "A silly nickname for your sibling",
  "Something that goes fast",
  "A sound you make when you stub your toe",
  "A thing that can fly but isn't alive",
  "A food you eat on a stick",
  "A place you go on a field trip",
  "Something you might find in a toy chest",
  "A dance you've tried to do",
  "Something that spins around and around",
  "A face people make when they're confused",
  "A funny way to fall asleep",
  "A food you put in a lunchbox",
  "A piece of clothing with buttons",
  "A thing you hear during fireworks",
  "A job you'd like to try for one day",
  "A tool used for painting",
  "Something you clap for",
  "A type of juice",
  "Something you find at a parade",
  "A place that's really quiet",
  "A place that's really loud",
  "A ride at a fair",
  "Something you write with",
  "A thing you'd find in the attic",
  "A way to move through water",
  "A word that starts with 'P'",
  "Something you'd see in a jungle",
  "A food you eat with chopsticks",
  "The name of a TV show you like",
  "Something you blow",
  "A silly hat",
  "A bird that can't fly",
  "A treat that melts",
  "A creature that hops",
  "A board game you've played",
  "Something you'd pack for the beach",
  "A tool a superhero might use",
  "A way to cool off on a hot day",
  "A movie you've watched as a family",
  "Something that jingles",
  "A sound you hear in the morning",
  "Something you decorate",
  "A word with only one syllable",
  "Something you stack",
  "A food that comes in a can",
  "A thing you'd find at the zoo",
  "A holiday you love",
  "A place where you hear music",
  "A smell you like at a bakery",
  "A creature with lots of legs",
  "A place you might go hiking",
  "A kind of sandwich",
  "A famous cartoon family",
  "Something round",
  "A silly rule someone made up",
  "A prize you'd want to win",
  "Something you draw with",
  "A place you'd like to build a treehouse",
  "A kind of cookie",
  "A costume you've worn before",
  "A way to make someone laugh",
  "A food you dip into something",
  "A food you could eat every day",
  "Something soft you want to cuddle"
];
