import { PlayerInGame } from "@resync-games/api";
import createHash from "create-hash";
import { capitalize } from "lodash-es";

const RED = "#f5b7b1";
const BLUE = "#a9cce3";
const GRAY = "#fff";

export function getTeamColor(team?: number) {
  if (team === undefined) {
    return GRAY;
  }

  if (team === 0) {
    return RED;
  }

  return BLUE;
}

function getNumber(seed: string): number {
  const hash = createHash("sha256").update(seed).digest("hex");
  return parseInt(hash, 16);
}

export function getTeamName(players: PlayerInGame[], team: number) {
  const teamPlayers = players.filter((p) => p.team === team);
  if (teamPlayers.length === 0) {
    return "None";
  }

  const seed = getNumber(teamPlayers.map((p) => p.playerId).join(""));

  const adjectiveSeed = seed % adjectives.length;
  const nounSeed = seed % nouns.length;

  return `${capitalize(adjectives[adjectiveSeed] ?? "")} ${capitalize(nouns[nounSeed] ?? "")}`;
}

const adjectives = [
  "zany",
  "quirky",
  "snazzy",
  "bubbly",
  "jazzy",
  "funky",
  "spunky",
  "zesty",
  "sassy",
  "groovy",
  "peppy",
  "spiffy",
  "witty",
  "wacky",
  "cheery",
  "swanky",
  "breezy",
  "plucky",
  "chipper",
  "perky",
  "dapper",
  "snappy",
  "gleeful",
  "spry",
  "chummy",
  "droll",
  "jolly",
  "chirpy",
  "whimsical",
  "frothy",
  "feisty",
  "snuggly",
  "frisky",
  "zippy",
  "glitzy",
  "bouncy",
  "cheeky",
  "poppy",
  "spicy",
  "jaunty",
  "mirthful",
  "fancy",
  "plush",
  "bold",
  "brisk",
  "playful",
  "punchy",
  "quirky",
  "whippy",
  "vivid",
  "crisp",
  "kooky",
  "breezy",
  "perky",
  "sparkly",
  "gleaming",
  "nimble",
  "sprightly",
  "lively",
  "hearty",
  "flashy",
  "dashing",
  "jovial",
  "radiant",
  "graceful",
  "upbeat",
  "wild",
  "rambunctious",
  "loopy",
  "effervescent",
  "sunny",
  "brilliant",
  "vivacious",
  "spunky",
  "exuberant",
  "animated",
  "charming",
  "giddy",
  "chic",
  "bold",
  "flamboyant",
  "cheerful",
  "imaginative",
  "dreamy",
  "jaunty",
  "lighthearted",
  "festive",
  "peppy",
  "bright",
  "vibrant",
  "energetic",
  "ebullient",
  "dynamic",
  "captivating",
  "magnetic",
  "sparkling",
  "frolicsome",
  "playful",
  "boisterous",
  "spirited",
  "euphoric",
  "optimistic",
  "glamorous"
];

const nouns = [
  "adventures",
  "antics",
  "whirlwinds",
  "giggles",
  "wizards",
  "sparks",
  "riddles",
  "jumbles",
  "whimsies",
  "treats",
  "marvels",
  "twists",
  "sizzles",
  "parades",
  "glimmers",
  "sprites",
  "wonders",
  "jazzes",
  "baubles",
  "miracles",
  "whirls",
  "jesters",
  "carnivals",
  "thrills",
  "blazes",
  "glows",
  "dramas",
  "jigsaws",
  "zests",
  "gadgets",
  "revels",
  "treasures",
  "mysteries",
  "fiestas",
  "jamborees",
  "glees",
  "puzzles",
  "sparkles",
  "dreams",
  "fables",
  "charms",
  "jaunts",
  "sagas",
  "jubilees",
  "whirls",
  "galaxies",
  "twinkles",
  "enigmas",
  "fantasies",
  "cosmoses",
  "odysseys",
  "spectacles",
  "delights",
  "gigs",
  "melodies",
  "flashes",
  "extravaganzas",
  "banters",
  "frolics",
  "thrills",
  "shows",
  "zephyrs",
  "gleams",
  "romps",
  "skits",
  "drifts",
  "pageants",
  "froths",
  "boons",
  "sunbeams",
  "scampers",
  "quirks",
  "shines",
  "hustles",
  "pops",
  "pixies",
  "ballads",
  "starlights",
  "gleams",
  "breezes",
  "flickers",
  "blooms",
  "swoops",
  "comets",
  "feasts",
  "ripples",
  "jewels",
  "dashes",
  "dazzles",
  "bubbles",
  "fiends",
  "hums",
  "drizzles",
  "shindigs",
  "glitzes",
  "muses",
  "revelries",
  "twists",
  "hoots",
  "mirages"
];
