name: CI checks

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '22.5.1'
        cache: "yarn"
    - run: corepack enable && yarn
      name: Install yarn
    - run: yarn ci
      name: Run checks
