name: CI checks

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: 'true'
    - uses: actions/setup-node@v4
      with:
        node-version: '22.5.1'
    - run: corepack enable && yarn
    - run: yarn ci
