name: Deploy

on:
  workflow_run:
    workflows: ["CI checks"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    name: Deploy to EC2
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - uses: actions/checkout@v2 
      - name: Deploy
        env:
            EC2_SECRET_KEY: ${{secrets.EC2_SECRET_KEY}}
            SSH_HOST: ${{secrets.SSH_HOST}}
            SSH_USER_NAME: ${{secrets.SSH_USER_NAME}}
      
        run: |
          echo "$EC2_SECRET_KEY" > EC2_SECRET_KEY && chmod 600 EC2_SECRET_KEY
          ssh -o StrictHostKeyChecking=no -i EC2_SECRET_KEY ${SSH_USER_NAME}@${SSH_HOST} 'source ~/.nvm/nvm.sh && cd resync-games && git pull && ./scripts/updateServer.sh'